version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://foodlens_user:foodlens_password@db:5432/foodlens_db
      - FLASK_ENV=development
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - ./backend/static/uploads:/app/static/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=foodlens_db
      - POSTGRES_USER=foodlens_user
      - POSTGRES_PASSWORD=foodlens_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  postgres_data:
